In [12]:
def even_number_printer(n):
  for i in range(10):
     if (i+1)%2==0:
        print(i+1)
    
even_number_printer(10)


2
4
6
8
10


In [15]:
a=[1,2,3]
b=[4,5,6]
c=[[1,2,3],[4,5,6]]
sum=0
for i in range(len(a)):
    sum+=a[i]*b[i]
print(sum)

32


In [24]:
#array creation
import numpy as np

a= np.array([1,2,3])
b= np.array([4,5,6])
c= np.array([[1,2,3],[4,5,6]])  
d=[1,2,3]  
#broadcasting(elementwise multiplication by 1 number)
a=a*2
print(a)
d=d*2
print(d)
b=b+2 #elementwise addition
print(b)
np.sqrt(a)
#np.log(a)

[2 4 6]
[1, 2, 3, 1, 2, 3]
[6 7 8]


array([1.41421356, 2.        , 2.44948974])

In [31]:
#slicing & indexing 
c=np.array([[1,2,3],[4,5,6]])
print(c[0]) 
print(c[0][0])
print(c[0][1])
print(c[1][1])
print(type(c[0][1]))
print(c[0,2])

[1 2 3]
1
2
5
<class 'numpy.int64'>
3


In [ ]:
#reshaping and aggregation
d=np.array([1,2,3,4,5,6])
print(d)
print(d.shape)
e=np.array([[1,2,3,4,5,6]])
print(e)
print(e.shape)
print(d.reshape(2,3))

[1 2 3 4 5 6]
(6,)
[[1 2 3 4 5 6]]
(1, 6)
[[1 2 3]
 [4 5 6]]


In [43]:
e=np.array([[1,2,3],[4,5,6]])
print(np.mean(e))
print(np.sum(e, axis=0))
print(np.sum(e, axis=1))
print(np.mean(e, axis=0))

3.5
[5 7 9]
[ 6 15]
[2.5 3.5 4.5]


In [ ]:
import numpy as np
import time
#calculation using pythin lists
N=1000000 
a=list(range(N))
b=list(range(N))

c=list(range(N))

time_start=time.time()
for i in range(len(a)):

     c[i]=a[i]*b[i]

     time_end=time.time()
     print("the total time taken is", time_end-time_start)

TypeError: unsupported operand type(s) for *: 'int' and 'range'